# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Matias Beckerle
tagline:          '1987'
description:      'Imagination will take you everywhere'
url:              http://matiasbeckerle.github.io

author:
  name:           'Matias Beckerle'
  url:            http://matiasbeckerle.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/matiasbeckerle

linkedin:         https://ar.linkedin.com/in/matiasbeckerle