encoding: "utf-8"
title: "Matias Beckerle"
tagline: "1987"
description: "Imagination will take you everywhere"
url: http://matiasbeckerle.github.io
paginate: 5
paginate_path: "/blog/page:num/"

# Gems
gems: [jekyll-paginate]
